### ISSUE TITLE
Not an Issue but a Question 

### ISSUE THREAD

**Issue by dark-faze** [ariopratomo/netflix-clone#2]
Did you get any error like "Access to XMLHttpRequest at 'https://api.themoviedb.org/3' from origin 'http://localhost:3002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." while getting request from API on browser console ? #2
 Closed

**Comment by ariopratomo** [comment]
no, i didn't get error like that
